name: Blade DangerJS

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pr-bundle-size:
    name: Bundle Size Report
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Use Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.1
      - name: Setup Cache & Install Dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build Blade React Production
        run: yarn run-s build:clean build:generate-types build:react-prod
        working-directory: packages/blade
      - name: Update Bundle Size Data
        run: yarn bundle-size
        working-directory: packages/blade
      - name: Danger
        run: yarn danger ci
        working-directory: packages/blade
        env:
          DANGER_GITHUB_API_TOKEN: ${{ env.GITHUB_ACCESS_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: 'true'

  master-bundle-size:
    name: Update Bundle Size Data
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Use Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.1
      - name: Create File
        run: touch b.json
        working-directory: packages/blade
      - name: Check if file is modified
        id: file-check
        run: if [ -n "$(git status a.json --porcelain)" ]; then echo "result=true" >> $GITHUB_OUTPUT; else echo "result=false" >> $GITHUB_OUTPUT; fi
        working-directory: packages/blade
      - name: Commit Updated Bundle Size Data
        if: ${{ steps.file-check.outputs.result == 'true' }}
        run: |
          git config user.email "tools+cibot@razorpay.com"
          git config user.name "rzpcibot"
          git add a.json
          git commit -m "chore: update bundle size data [skip ci]"
          git push
        working-directory: packages/blade
